### ISSUE TITLE
Could you provide libDOtherSide.dll 

### ISSUE THREAD

**Issue by xland** [filcuc/DOtherSide#25] opened 2015-09-05 07:23 UTC
It is difficult to compile DOtherSide in windows environment.
Could you provide libDOtherSide.dll,please.
Thank you~

**Comment by filcuc** [comment] 2015-09-05 08:30
Did you happen to succeed in building it or not?
In reality it's not so difficult, but i can understand that it could be for someone who never built C++ Qt stuff on windows. To be honest i don't really like the idea to maintain a set of .dll for a specific platform with multiple compilers. Like one build for VS2013/ VS2015, MinGW etc.

I think we can arrive at a better compromise: improve the documentation with explicit references with the build instructions on windows. I can accept pull requests if you already succedded in building on windows and willing to help.

However here it's a simple list of instructions:
1) Install CMake 3.2 
2) Install Qt from the online installer
3) Clone the project
4) Open the CMakeLists.txt with the cmake app and set the build directory where you prefear
5) Click configure. Often this step fails if Qt isn't in your PATH. If it fails you should have some red marked variables that refears to the Qt modules like QtWidgets, QtQuick etc.
6) Set the value of each module to the corrisponding directory in Qt installation path. So if the variables in the CMake gui refears to QtWidgets it must point to the following path 
C:\path\to\qtinstallation\5.5\gcc_64\lib\cmake\Qt5Widgets 
The previous example implies Qt with version 5.5 and gcc (the compiler should be different if you installed Qt for visual studio).
7) Once you set all the variables, just reclick "Configure" and cmake should succeed
8) Click generate
9) Go to build-directory and build (if you choose the visual studio generation you should have the .sln read to be opened in VS otherwise use a MinGW shell and type mingw32-make)

**Comment by filcuc** [comment] 2015-09-05 08:32
in general i would like to set up and automated solution for all platforms. Very much like Travis CI with windows support or TeamCity. But it didn't find any service that let me do this online for free.

**Comment by filcuc** [comment] 2015-09-05 08:34
if you agree with me i prefear to close this issue and open another one titled "Add documentation in how to build DOtherSide on supported platforms: Windows and Linux"

**Comment by xland** [comment] 2015-09-05 09:07
Yes,I want to share the build instructions on windows when I can manage that.
Thank you for Help~
-----------------------------My Compile Error-------------------------------
D:\nim\nimqml\DOtherSide\DOtherSide>cmake CMakeLists.txt
-- Building for: Visual Studio 14 2015
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.



CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.2)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "D:/nim/nimqml/DOtherSide/DOtherSide/CMakeFiles/CMakeOutput.log".
See also "D:/nim/nimqml/DOtherSide/DOtherSide/CMakeFiles/CMakeError.log".

**Comment by filcuc** [comment] 2015-09-05 10:21
The C++ compiler is not found. With which compiler are you going to build the .dll ? it should match the one you downloaded Qt: Visual studio or MinGW?
Visual Studio: if you are using visual studio DON'T use the command line as you're doing there!! i mean, yes you can use the command line but it implies that you must open a prompt into which the visual studio has been added to the PATH variable (usually you find in Start->Programs something like Visual Studio 2010 Command Prompt or something like that). The easier thing to do it's to open the CMake GUI (so don't use the command line). And proceed with the steps i written before. Usually the first time you do so CMake ask you which compiler to use.

**Comment by xland** [comment] 2015-09-05 12:40
YES!
I got the "DOtherSide.dll" finally.
And I compile the "HelloWorld" example with "nim c -r --app: gui  main.nim"
But the "main.exe" can not be executed,
When I copy the "main.exe","DOtherSide.dll" and "main.qml" to the "C:\Qt\5.5\msvc2012\bin" directory
the "main.exe" can not be executed too.

Thank you.

**Comment by filcuc** [comment] 2015-09-05 12:43
Wait wait wait.
When you build the DOtherSide project you usually build three things:
1) the DOtherSide.dll
2) the d bindings
3) the nim bindings

did you build only (1) or also the other (2)?

**Comment by filcuc** [comment] 2015-09-05 12:44
sorry i meant (3)

**Comment by filcuc** [comment] 2015-09-05 12:49
because in nim you need also to  install the NimQml module (as specified in the doc) as specified in the installation instructions

```
For the NimQml module you can use the nimble package manager

nimble install NimQml

or

cd to/build/dir/Nim/NimQml
nimble install


```

**Comment by filcuc** [comment] 2015-09-05 12:51
and btw what do you mean with "the main.exe cannot be executed"?

**Comment by filcuc** [comment] 2015-09-05 12:56
supposing you have installed also the NimQml module please try to compile this way:

nim c --threads:on main.nim

**Comment by xland** [comment] 2015-09-05 13:07
1) My Vs project has three sub projects: "ALL_BUILD","DOtherSide","ZERO_CHECK"
2) When I builded my project,There were just three files in my release directory:"DOtherSide.dll","DOtherSide.exp","DOtherSide.lib"
3) I copy "NimQml.nim","NimQmlMacros.nim","NimQmlTypes.nim","main.nim","main.qml","DOtherSide.dll" these files to the same directory. And then I excute  "nim c -r --app: gui main.nim".
And I get this info:"Hint: operation successful (19256 lines compiled; 4.557 sec total; 19.194MB; Debug Build) [SuccessX]"
4)"the main.exe cannot be executed": I double click the main.exe.Noting happend.
5)"nim c --threads:on main.nim" is as same as 4)

**Comment by filcuc** [comment] 2015-09-05 13:11
can you execute it from the command line? and see if there's any debug
error?
to me it sounds a sort of mix between mingw and visual studio.
Double check it with http://www.dependencywalker.com/
this program tells you the .exe needed .dlls

2015-09-05 15:07 GMT+02:00 liulun <notifications@github.com>:

> 1) My Vs project has three sub projects:
> "ALL_BUILD","DOtherSide","ZERO_CHECK"
> 2) When I builded my project,There were just three files in my release
> directory:"DOtherSide.dll","DOtherSide.exp","DOtherSide.lib"
> 3) I copy
> "NimQml.nim","NimQmlMacros.nim","NimQmlTypes.nim","main.nim","main.qml","DOtherSide.dll"
> these files to the same directory. And then I excute "nim c -r --app: gui
> main.nim".
> And I get this info:"Hint: operation successful (19256 lines compiled;
> 4.557 sec total; 19.194MB; Debug Build) [SuccessX]"
> 4)"the main.exe cannot be executed": I double click the main.exe.Noting
> happend.
> 5)"nim c --threads:on main.nim" is as same as 4)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filcuc/DOtherSide/issues/25#issuecomment-137952610>.
>



-- 
Filippo Cucchetto

**Comment by filcuc** [comment] 2015-09-05 13:16
try this way
nim cpp --threads:on --cc=vcc main.nim

this should force to use the Visual Studio cpp compiler

2015-09-05 15:11 GMT+02:00 Filippo Cucchetto <filippocucchetto@gmail.com>:

> can you execute it from the command line? and see if there's any debug
> error?
> to me it sounds a sort of mix between mingw and visual studio.
> Double check it with http://www.dependencywalker.com/
> this program tells you the .exe needed .dlls
>
> 2015-09-05 15:07 GMT+02:00 liulun <notifications@github.com>:
>
>> 1) My Vs project has three sub projects:
>> "ALL_BUILD","DOtherSide","ZERO_CHECK"
>> 2) When I builded my project,There were just three files in my release
>> directory:"DOtherSide.dll","DOtherSide.exp","DOtherSide.lib"
>> 3) I copy
>> "NimQml.nim","NimQmlMacros.nim","NimQmlTypes.nim","main.nim","main.qml","DOtherSide.dll"
>> these files to the same directory. And then I excute "nim c -r --app: gui
>> main.nim".
>> And I get this info:"Hint: operation successful (19256 lines compiled;
>> 4.557 sec total; 19.194MB; Debug Build) [SuccessX]"
>> 4)"the main.exe cannot be executed": I double click the main.exe.Noting
>> happend.
>> 5)"nim c --threads:on main.nim" is as same as 4)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/filcuc/DOtherSide/issues/25#issuecomment-137952610>.
>>
>
>
>
> --
> Filippo Cucchetto
>



-- 
Filippo Cucchetto

**Comment by xland** [comment] 2015-09-05 13:30
1)
"nim cpp --threads:on --cc=vcc main.nim": compile error with unreadble error: OS error: 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?

2)
dependency walker:
Error: At least one required implicit or forwarded dependency was not found.
Warning: At least one delay-load dependency module was not found.
too many to list.................

**Comment by xland** [comment] 2015-09-05 13:32
execute it from the command line:
no error was shown too

**Comment by filcuc** [comment] 2015-09-05 13:33
nim cpp --cc=vcc main.nim
must work. If it doesn't than you have to open the visual studio shell.
Which visual studio are you using?

2015-09-05 15:32 GMT+02:00 liulun <notifications@github.com>:

> execute it from the command line:
> no error was shown too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filcuc/DOtherSide/issues/25#issuecomment-137956410>.
>



-- 
Filippo Cucchetto

**Comment by filcuc** [comment] 2015-09-05 13:35
This article for VS2013 explains in the beginning how to open the Developer
Command Prompt
https://msdn.microsoft.com/en-us/library/f35ctcxw%28v=vs.120%29.aspx

2015-09-05 15:33 GMT+02:00 Filippo Cucchetto <filippocucchetto@gmail.com>:

> nim cpp --cc=vcc main.nim
> must work. If it doesn't than you have to open the visual studio shell.
> Which visual studio are you using?
>
> 2015-09-05 15:32 GMT+02:00 liulun <notifications@github.com>:
>
>> execute it from the command line:
>> no error was shown too
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/filcuc/DOtherSide/issues/25#issuecomment-137956410>.
>>
>
>
>
> --
> Filippo Cucchetto
>



-- 
Filippo Cucchetto

**Comment by filcuc** [comment] 2015-09-05 13:37
and please put online the screenshot of dependency walker with all the dll in left panel collapsed

**Comment by filcuc** [comment] 2015-09-05 13:37
You can post it here
http://picpaste.com/

**Comment by xland** [comment] 2015-09-05 13:40
dependency module was not found:

API-MS-WIN-CORE-APPCOMPAT-L1-1-1.DLL
API-MS-WIN-CORE-APPINIT-L1-1-0.DLL
API-MS-WIN-CORE-ATOMS-L1-1-0.DLL
API-MS-WIN-CORE-COMM-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L2-1-0.DLL
API-MS-WIN-CORE-DATETIME-L1-1-1.DLL
API-MS-WIN-CORE-DATETIME-L1-1-2.DLL
API-MS-WIN-CORE-DEBUG-L1-1-1.DLL
API-MS-WIN-CORE-DELAYLOAD-L1-1-1.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-1.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-3.DLL
API-MS-WIN-CORE-FIBERS-L1-1-1.DLL
API-MS-WIN-CORE-FIBERS-L2-1-1.DLL
API-MS-WIN-CORE-FILE-L1-2-1.DLL
API-MS-WIN-CORE-FILE-L1-2-2.DLL
API-MS-WIN-CORE-FILE-L2-1-1.DLL
API-MS-WIN-CORE-FILE-L2-1-2.DLL
API-MS-WIN-CORE-HANDLE-L1-1-0.DLL
API-MS-WIN-CORE-HEAP-L1-2-0.DLL
API-MS-WIN-CORE-HEAP-L2-1-0.DLL
API-MS-WIN-CORE-HEAP-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-IO-L1-1-1.DLL
API-MS-WIN-CORE-JOB-L1-1-0.DLL
API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-1.DLL
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-1.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-1.DLL
API-MS-WIN-CORE-LOCALIZATION-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-OBSOLETE-L1-3-0.DLL
API-MS-WIN-CORE-LOCALIZATION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-2.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-0.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-1.DLL
API-MS-WIN-CORE-NAMESPACE-L1-1-0.DLL
API-MS-WIN-CORE-NORMALIZATION-L1-1-0.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-2-0.DLL
API-MS-WIN-CORE-PROCESSSNAPSHOT-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-2.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-3.DLL
API-MS-WIN-CORE-PROCESSTOPOLOGY-L1-2-0.DLL
API-MS-WIN-CORE-PROFILE-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-ANSI-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-L1-1-0.DLL
API-MS-WIN-CORE-REALTIME-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L1-1-0.DLL
API-MS-WIN-CORE-RTLSUPPORT-L1-2-0.DLL
API-MS-WIN-CORE-SIDEBYSIDE-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L2-1-0.DLL
API-MS-WIN-CORE-STRING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-STRINGANSI-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-1.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-1.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-3.DLL
API-MS-WIN-CORE-SYSTEMTOPOLOGY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-TIMEZONE-L1-1-0.DLL
API-MS-WIN-CORE-UTIL-L1-1-0.DLL
API-MS-WIN-CORE-WINDOWSERRORREPORTING-L1-1-0.DLL
API-MS-WIN-CORE-WOW64-L1-1-0.DLL
API-MS-WIN-CORE-WOW64-L1-1-1.DLL
API-MS-WIN-CORE-XSTATE-L2-1-0.DLL
API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL
API-MS-WIN-SECURITY-APPCONTAINER-L1-1-0.DLL
API-MS-WIN-SECURITY-BASE-L1-2-0.DLL
API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
API-MS-WIN-CORE-COM-L1-1-1.DLL
API-MS-WIN-CORE-CRT-L1-1-0.DLL
API-MS-WIN-CORE-CRT-L2-1-0.DLL
API-MS-WIN-CORE-INTERLOCKED-L1-2-0.DLL
API-MS-WIN-CORE-REGISTRY-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-L1-2-0.DLL
API-MS-WIN-CORE-VERSION-L1-1-0.DLL
API-MS-WIN-DEVICES-CONFIG-L1-1-1.DLL
API-MS-WIN-DEVICES-QUERY-L1-1-1.DLL
API-MS-WIN-EVENTING-CLASSICPROVIDER-L1-1-0.DLL
API-MS-WIN-EVENTING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-POWER-BASE-L1-1-0.DLL
API-MS-WIN-POWER-SETTING-L1-1-0.DLL
API-MS-WIN-SECURITY-GROUPPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L1-1-1.DLL
API-MS-WIN-SECURITY-LSAPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-SDDL-L1-1-0.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L1-1-0.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L2-1-0.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-SERVICE-WINSVC-L1-2-0.DLL
EXT-MS-WIN-ADVAPI32-NPUSERNAME-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-NTMARTA-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-APPMODEL-APPCONTAINERPATH-L1-1-0.DLL
EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOY-L1-1-0.DLL
EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOYONECORE-L1-1-0.DLL
EXT-MS-WIN-AUTHZ-CONTEXT-L1-1-0.DLL
EXT-MS-WIN-CORE-WINRT-REMOTE-L1-1-0.DLL
EXT-MS-WIN-FECLIENT-ENCRYPTEDFILE-L1-1-0.DLL
EXT-MS-WIN-GPAPI-GROUPPOLICY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-APPCOMPAT-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-DATETIME-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-ERRORHANDLING-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-FILE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-1.DLL
EXT-MS-WIN-KERNEL32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-SIDEBYSIDE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-1.DLL
EXT-MS-WIN-KERNELBASE-PROCESSTHREAD-L1-1-0.DLL
EXT-MS-WIN-MRMCORER-RESMANAGER-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-1.DLL
EXT-MS-WIN-NTUSER-MESSAGE-L1-1-1.DLL
EXT-MS-WIN-NTUSER-MISC-L1-5-0.DLL
EXT-MS-WIN-NTUSER-STRING-L1-1-0.DLL
EXT-MS-WIN-NTUSER-SYNCH-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOW-L1-1-1.DLL
EXT-MS-WIN-PROFILE-EXTENDER-L1-1-0.DLL
EXT-MS-WIN-PROFILE-LOAD-L1-1-0.DLL
EXT-MS-WIN-RPC-SSL-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-SYSPARAMS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-WINDOW-EXT-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CAPAUTHZ-L1-1-0.DLL
EXT-MS-WIN-SHELL32-SHELLCOM-L1-1-0.DLL

**Comment by filcuc** [comment] 2015-09-05 13:42
this doesn't mean anything. Please put a screenshot online

2015-09-05 15:40 GMT+02:00 liulun <notifications@github.com>:

> dependency module was not found:
>
> API-MS-WIN-CORE-APPCOMPAT-L1-1-1.DLL
> API-MS-WIN-CORE-APPINIT-L1-1-0.DLL
> API-MS-WIN-CORE-ATOMS-L1-1-0.DLL
> API-MS-WIN-CORE-COMM-L1-1-0.DLL
> API-MS-WIN-CORE-CONSOLE-L1-1-0.DLL
> API-MS-WIN-CORE-CONSOLE-L2-1-0.DLL
> API-MS-WIN-CORE-DATETIME-L1-1-1.DLL
> API-MS-WIN-CORE-DATETIME-L1-1-2.DLL
> API-MS-WIN-CORE-DEBUG-L1-1-1.DLL
> API-MS-WIN-CORE-DELAYLOAD-L1-1-1.DLL
> API-MS-WIN-CORE-ERRORHANDLING-L1-1-1.DLL
> API-MS-WIN-CORE-ERRORHANDLING-L1-1-3.DLL
> API-MS-WIN-CORE-FIBERS-L1-1-1.DLL
> API-MS-WIN-CORE-FIBERS-L2-1-1.DLL
> API-MS-WIN-CORE-FILE-L1-2-1.DLL
> API-MS-WIN-CORE-FILE-L1-2-2.DLL
> API-MS-WIN-CORE-FILE-L2-1-1.DLL
> API-MS-WIN-CORE-FILE-L2-1-2.DLL
> API-MS-WIN-CORE-HANDLE-L1-1-0.DLL
> API-MS-WIN-CORE-HEAP-L1-2-0.DLL
> API-MS-WIN-CORE-HEAP-L2-1-0.DLL
> API-MS-WIN-CORE-HEAP-OBSOLETE-L1-1-0.DLL
> API-MS-WIN-CORE-IO-L1-1-1.DLL
> API-MS-WIN-CORE-JOB-L1-1-0.DLL
> API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-1.DLL
> API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
> API-MS-WIN-CORE-LIBRARYLOADER-L1-2-0.DLL
> API-MS-WIN-CORE-LIBRARYLOADER-L1-2-1.DLL
> API-MS-WIN-CORE-LIBRARYLOADER-L2-1-0.DLL
> API-MS-WIN-CORE-LOCALIZATION-L1-2-1.DLL
> API-MS-WIN-CORE-LOCALIZATION-L2-1-0.DLL
> API-MS-WIN-CORE-LOCALIZATION-OBSOLETE-L1-3-0.DLL
> API-MS-WIN-CORE-LOCALIZATION-PRIVATE-L1-1-0.DLL
> API-MS-WIN-CORE-MEMORY-L1-1-2.DLL
> API-MS-WIN-CORE-NAMEDPIPE-L1-2-0.DLL
> API-MS-WIN-CORE-NAMEDPIPE-L1-2-1.DLL
> API-MS-WIN-CORE-NAMESPACE-L1-1-0.DLL
> API-MS-WIN-CORE-NORMALIZATION-L1-1-0.DLL
> API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
> API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-2-0.DLL
> API-MS-WIN-CORE-PROCESSSNAPSHOT-L1-1-0.DLL
> API-MS-WIN-CORE-PROCESSTHREADS-L1-1-2.DLL
> API-MS-WIN-CORE-PROCESSTHREADS-L1-1-3.DLL
> API-MS-WIN-CORE-PROCESSTOPOLOGY-L1-2-0.DLL
> API-MS-WIN-CORE-PROFILE-L1-1-0.DLL
> API-MS-WIN-CORE-PSAPI-ANSI-L1-1-0.DLL
> API-MS-WIN-CORE-PSAPI-L1-1-0.DLL
> API-MS-WIN-CORE-REALTIME-L1-1-0.DLL
> API-MS-WIN-CORE-REGISTRY-L1-1-0.DLL
> API-MS-WIN-CORE-RTLSUPPORT-L1-2-0.DLL
> API-MS-WIN-CORE-SIDEBYSIDE-L1-1-0.DLL
> API-MS-WIN-CORE-STRING-L1-1-0.DLL
> API-MS-WIN-CORE-STRING-L2-1-0.DLL
> API-MS-WIN-CORE-STRING-OBSOLETE-L1-1-0.DLL
> API-MS-WIN-CORE-STRINGANSI-L1-1-0.DLL
> API-MS-WIN-CORE-SYNCH-L1-2-0.DLL
> API-MS-WIN-CORE-SYNCH-L1-2-1.DLL
> API-MS-WIN-CORE-SYSINFO-L1-2-1.DLL
> API-MS-WIN-CORE-SYSINFO-L1-2-3.DLL
> API-MS-WIN-CORE-SYSTEMTOPOLOGY-L1-1-0.DLL
> API-MS-WIN-CORE-THREADPOOL-LEGACY-L1-1-0.DLL
> API-MS-WIN-CORE-THREADPOOL-PRIVATE-L1-1-0.DLL
> API-MS-WIN-CORE-TIMEZONE-L1-1-0.DLL
> API-MS-WIN-CORE-UTIL-L1-1-0.DLL
> API-MS-WIN-CORE-WINDOWSERRORREPORTING-L1-1-0.DLL
> API-MS-WIN-CORE-WOW64-L1-1-0.DLL
> API-MS-WIN-CORE-WOW64-L1-1-1.DLL
> API-MS-WIN-CORE-XSTATE-L2-1-0.DLL
> API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL
> API-MS-WIN-SECURITY-APPCONTAINER-L1-1-0.DLL
> API-MS-WIN-SECURITY-BASE-L1-2-0.DLL
> API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
> API-MS-WIN-CORE-COM-L1-1-1.DLL
> API-MS-WIN-CORE-CRT-L1-1-0.DLL
> API-MS-WIN-CORE-CRT-L2-1-0.DLL
> API-MS-WIN-CORE-INTERLOCKED-L1-2-0.DLL
> API-MS-WIN-CORE-REGISTRY-PRIVATE-L1-1-0.DLL
> API-MS-WIN-CORE-THREADPOOL-L1-2-0.DLL
> API-MS-WIN-CORE-VERSION-L1-1-0.DLL
> API-MS-WIN-DEVICES-CONFIG-L1-1-1.DLL
> API-MS-WIN-DEVICES-QUERY-L1-1-1.DLL
> API-MS-WIN-EVENTING-CLASSICPROVIDER-L1-1-0.DLL
> API-MS-WIN-EVENTING-OBSOLETE-L1-1-0.DLL
> API-MS-WIN-POWER-BASE-L1-1-0.DLL
> API-MS-WIN-POWER-SETTING-L1-1-0.DLL
> API-MS-WIN-SECURITY-GROUPPOLICY-L1-1-0.DLL
> API-MS-WIN-SECURITY-LSALOOKUP-L1-1-1.DLL
> API-MS-WIN-SECURITY-LSAPOLICY-L1-1-0.DLL
> API-MS-WIN-SECURITY-SDDL-L1-1-0.DLL
> API-MS-WIN-SERVICE-MANAGEMENT-L1-1-0.DLL
> API-MS-WIN-SERVICE-MANAGEMENT-L2-1-0.DLL
> API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
> API-MS-WIN-SERVICE-WINSVC-L1-2-0.DLL
> EXT-MS-WIN-ADVAPI32-NPUSERNAME-L1-1-0.DLL
> EXT-MS-WIN-ADVAPI32-NTMARTA-L1-1-0.DLL
> EXT-MS-WIN-ADVAPI32-REGISTRY-L1-1-0.DLL
> EXT-MS-WIN-APPMODEL-APPCONTAINERPATH-L1-1-0.DLL
> EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOY-L1-1-0.DLL
> EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOYONECORE-L1-1-0.DLL
> EXT-MS-WIN-AUTHZ-CONTEXT-L1-1-0.DLL
> EXT-MS-WIN-CORE-WINRT-REMOTE-L1-1-0.DLL
> EXT-MS-WIN-FECLIENT-ENCRYPTEDFILE-L1-1-0.DLL
> EXT-MS-WIN-GPAPI-GROUPPOLICY-L1-1-0.DLL
> EXT-MS-WIN-KERNEL32-APPCOMPAT-L1-1-0.DLL
> EXT-MS-WIN-KERNEL32-DATETIME-L1-1-0.DLL
> EXT-MS-WIN-KERNEL32-ERRORHANDLING-L1-1-0.DLL
> EXT-MS-WIN-KERNEL32-FILE-L1-1-0.DLL
> EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-0.DLL
> EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-1.DLL
> EXT-MS-WIN-KERNEL32-REGISTRY-L1-1-0.DLL
> EXT-MS-WIN-KERNEL32-SIDEBYSIDE-L1-1-0.DLL
> EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-0.DLL
> EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-1.DLL
> EXT-MS-WIN-KERNELBASE-PROCESSTHREAD-L1-1-0.DLL
> EXT-MS-WIN-MRMCORER-RESMANAGER-L1-1-0.DLL
> EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
> EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-1.DLL
> EXT-MS-WIN-NTUSER-MESSAGE-L1-1-1.DLL
> EXT-MS-WIN-NTUSER-MISC-L1-5-0.DLL
> EXT-MS-WIN-NTUSER-STRING-L1-1-0.DLL
> EXT-MS-WIN-NTUSER-SYNCH-L1-1-0.DLL
> EXT-MS-WIN-NTUSER-WINDOW-L1-1-1.DLL
> EXT-MS-WIN-PROFILE-EXTENDER-L1-1-0.DLL
> EXT-MS-WIN-PROFILE-LOAD-L1-1-0.DLL
> EXT-MS-WIN-RPC-SSL-L1-1-0.DLL
> EXT-MS-WIN-RTCORE-NTUSER-SYSPARAMS-L1-1-0.DLL
> EXT-MS-WIN-RTCORE-NTUSER-WINDOW-EXT-L1-1-0.DLL
> EXT-MS-WIN-SECURITY-CAPAUTHZ-L1-1-0.DLL
> EXT-MS-WIN-SHELL32-SHELLCOM-L1-1-0.DLL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filcuc/DOtherSide/issues/25#issuecomment-137957259>.
>



-- 
Filippo Cucchetto

**Comment by xland** [comment] 2015-09-05 13:49
![Image of wd](http://www.lvkangzixun.net/cndzys/cndzys/wd.png)

**Comment by filcuc** [comment] 2015-09-05 13:53
i told you to collapse the tree in the left panel: so collapse the
User32.dll node and leave the root Main.exe open and redo the screenshot.

However you must open a Developer Prompt of visual studio and compile the
main.nim with
nim cpp --cc=vcc main.nim

2015-09-05 15:49 GMT+02:00 liulun <notifications@github.com>:

> [image: Image of wd]
> <https://camo.githubusercontent.com/57398dbe0490c3f4c0e6d112b993e381def5f51f/687474703a2f2f7777772e6c766b616e677a6978756e2e6e65742f636e647a79732f636e647a79732f77642e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filcuc/DOtherSide/issues/25#issuecomment-137957622>.
>



-- 
Filippo Cucchetto

**Comment by filcuc** [comment] 2015-09-05 13:54
if you have TeamViewer i can try to fix it for you

2015-09-05 15:53 GMT+02:00 Filippo Cucchetto <filippocucchetto@gmail.com>:

> i told you to collapse the tree in the left panel: so collapse the
> User32.dll node and leave the root Main.exe open and redo the screenshot.
>
> However you must open a Developer Prompt of visual studio and compile the
> main.nim with
> nim cpp --cc=vcc main.nim
>
> 2015-09-05 15:49 GMT+02:00 liulun <notifications@github.com>:
>
>> [image: Image of wd]
>> <https://camo.githubusercontent.com/57398dbe0490c3f4c0e6d112b993e381def5f51f/687474703a2f2f7777772e6c766b616e677a6978756e2e6e65742f636e647a79732f636e647a79732f77642e706e67>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/filcuc/DOtherSide/issues/25#issuecomment-137957622>.
>>
>
>
>
> --
> Filippo Cucchetto
>



-- 
Filippo Cucchetto

**Comment by xland** [comment] 2015-09-05 13:59
USER32.DLL is the last dll........
Thanks for your help.
But I must go to bed now
It is too late in China.
Sorry.

**Comment by filcuc** [comment] 2015-09-05 18:36
ok so i recorded this video and pushed a fix in master
if you follow it correctly from start to end you shuould be set 
https://www.youtube.com/watch?v=SORBYN7vOxQ

**Comment by filcuc** [comment] 2015-09-07 21:48
The video is there. I think that you have a mess caused by mixing visual studio, mingw, Qt and maybe also differenti architecture. Please take a look at the video and confirm me if it solves your problems. Otherwise reopen this issue.

**Closed by filcuc** 2015-09-07 21:48 UTC

**Comment by xland** [comment] 2015-09-08 02:42
I still haven't watched it.
My VPN is out of time,
(You know, In China, If you want to visit  youtube, you must have an VPN )

**Comment by filcuc** [comment] 2015-09-08 11:50
I dind't heard anything from you so i didn't know. 
I've no problem in hosting the file .avi for direct download through my Copy cloud provider.
i'll give you the link late this evening.

Cheers

**Comment by xland** [comment] 2015-09-08 12:09
OK~
Thank you very much

**Comment by filcuc** [comment] 2015-09-11 18:01
i've sent you and email with Copy with the view address

**Comment by xland** [comment] 2015-09-12 13:16
error info from copy.com
"Sorry, you do not have access to this privately shared content."

**Comment by filcuc** [comment] 2015-09-12 14:44
https://copy.com/Yxt70hQJvpqLLnBW

**Comment by xland** [comment] 2015-09-13 11:24
Ok,I'll try it a few days later.

**Comment by filcuc** [comment] 2015-09-13 11:49
Ok
